# Generated by Django 5.0.6 on 2024-05-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interet',
            field=models.ManyToManyField(to='app_1.interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_de_profil',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
