# Generated by Django 5.0.6 on 2024-06-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_profile_sexe_alter_profile_date_naissance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_naissance',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
