# Generated by Django 5.0.6 on 2024-06-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_remove_profile_date_naissance_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interet',
            field=models.ManyToManyField(blank=True, to='app_1.interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=8, null=True),
        ),
    ]
