# Generated by Django 5.0.6 on 2024-06-10 10:53

from django.db import migrations, models


def create_default_interests(apps, schema_editor):
    Interest = apps.get_model('app_1', 'Interest')
    default_interests = ['Sports', 
                         'Musique',
                         'Lecture',
                         'Voyage',
                         'Cuisine',
                         'Art',
                         'Technologie']
    for interest in default_interests:
        Interest.objects.get_or_create(name=interest)


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_profile_interet_alter_profile_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_de_profil',
            field=models.ImageField(null=True, upload_to='profile_pictures'),
        ),
        migrations.RunPython(create_default_interests),
    ]
