# Generated by Django 5.0.6 on 2024-06-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_rename_interet_profile_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='interest',
            new_name='interet',
        ),
    ]
