# Generated by Django 5.0.6 on 2024-06-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_rename_demarrée_le_conversation_demarree_le'),
        ('app_1', '0008_rename_interest_profile_interet'),
    ]

    operations = [
    ]
