# Generated by Django 5.0.6 on 2024-06-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_merge_20240614_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
