# Generated by Django 5.0.6 on 2024-06-17 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_merge_20240614_1936'),
        ('app_1', '0010_remove_message_conversation_and_more'),
    ]

    operations = [
    ]
