# Generated by Django 5.0.6 on 2024-06-13 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_room_friendname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='friendName',
        ),
        migrations.RemoveField(
            model_name='room',
            name='friendSlug',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_online',
        ),
        migrations.AddField(
            model_name='room',
            name='friends',
            field=models.ManyToManyField(related_name='chatRoom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatapp.room'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
