# Generated by Django 5.0.6 on 2024-06-13 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_remove_room_friendname_remove_room_friendslug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='friends',
            field=models.ManyToManyField(related_name='friendRoom', to=settings.AUTH_USER_MODEL),
        ),
    ]
