# Generated by Django 5.0.6 on 2024-06-13 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_room_friends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='chatRoom',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatapp.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_reçus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
